Repository boklisten/bl-api, pull requests merged in 2024-01, with the labels that each got.

#482 feat(message): add support for custom SMS reminder text
  package.json
  src/auth/local/local-login.validator.spec.ts
  src/auth/token/token.handler.spec.ts
  src/auth/user/user-provider/user-provider.spec.ts
  src/auth/user/user.handler.spec.ts
  src/auth/user/user.handler.ts
  src/bl-error/bl-error-handler.ts
  src/collections/email-validation/helpers/email-validation.helper.spec.ts
  src/collections/email-validation/helpers/email-validation.helper.ts
  src/collections/email-validation/hooks/email-validation-post.hook.spec.ts
  src/collections/message/hooks/message-post.hook.spec.ts
  src/collections/message/hooks/message-post.hook.ts
  src/collections/order/helpers/order-placed-handler/order-placed-handler.spec.ts
  src/collections/order/helpers/order-placed-handler/order-placed-handler.ts
  src/messenger/email/email-service.ts
  src/messenger/email/order-email/order-email-handler.spec.ts
  src/messenger/email/order-email/order-email-handler.ts
  src/messenger/messenger.ts
  src/messenger/reminder/messenger-reminder.ts
  yarn.lock
Labels: enhancement

#483 Bump Mongoose And MongoDB Driver To Latest
  fixtures/branches.ts
  fixtures/items.ts
  fixtures/locallogins.ts
  fixtures/openinghours.ts
  fixtures/userdetails.ts
  fixtures/users.ts
  package.json
  src/auth/local/local-login.validator.spec.ts
  src/collections/booking/booking.schema.ts
  src/collections/branch-item/branch-item.schema.ts
  src/collections/branch/branch.schema.ts
  src/collections/branch/operations/branch-booking-times.operation.ts
  src/collections/customer-item/customer-item.schema.ts
  src/collections/customer-item/helpers/customer-item-handler.spec.ts
  src/collections/customer-item/helpers/customer-item-handler.ts
  src/collections/email-validation/email-validation.schema.ts
  src/collections/match/match.schema.ts
  src/collections/message/message.schema.ts
  src/collections/order/operations/place/order-place.operation.ts
  src/collections/order/order.schema.ts
  src/collections/pending-password-reset/pending-password-reset.schema.ts
  src/collections/unique-item/unique-item.schema.ts
  src/collections/user-detail/user-detail.schema.ts
  src/collections/user/user.schema.ts
  src/collections/user/user.ts
  src/query/object-id-filter/db-query-object-id-filter.spec.ts
  src/server/server.ts
  src/storage/blDocumentStorage.ts
  src/storage/blStorageHandler.ts
  src/storage/mongoDb/mongoDb.blStorageHandler.ts
  src/storage/mongoDb/mongoose-schema-creator.ts
  src/storage/nested-document.ts
  yarn.lock
Labels: enhancement, dependencies

#484 Add API-endpoints for user-facing editable text
  package.json
  src/collection-endpoint/collection-endpoint-creator.ts
  src/collection-endpoint/collection-endpoint-document/collection-endpoint-document-auth.spec.ts
  src/collection-endpoint/collection-endpoint-document/collection-endpoint-document-auth.ts
  src/collection-endpoint/collection-endpoint-operation.ts
  src/collection-endpoint/collection-endpoint-put/collection-endpoint-put.ts
  src/collection-endpoint/collection-endpoint.ts
  src/collections/bl-collection.ts
  src/collections/editable-text/editable-text.collection.ts
  src/collections/editable-text/editable-text.schema.ts
  src/collections/editable-text/hooks/editable-text.put.hook.ts
  src/endpoint/bl-endpoint-method.ts
  src/endpoint/bl-endpoint-operation.ts
  src/endpoint/bl-endpoint-restriction.ts
  src/endpoint/bl-endpoint.ts
  src/storage/blDocumentStorage.ts
  src/storage/mongoDb/mongoDb.blStorageHandler.ts
  src/storage/mongoDb/mongoose-schema-creator.ts
  yarn.lock
Labels: enhancement

#485 fix(customer-item.schema): reintroduce default false values
  src/collections/customer-item/customer-item.schema.ts
Labels: bug
